# -*- coding: utf-8 -*-
"""DiseñarunModelodeDistribuciónInteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Veb272kpiqI7Lpq5PZACi4L9eNgbJFD4
"""

import pandas as pd
import numpy as np

# Fijamos una semilla para que los datos aleatorios sean siempre los mismos
np.random.seed(0)

# 1. Definimos la cantidad de expedientes (clientes)
n_expedientes = 12000

# 2. Generamos las 4 variables clave que nos pide el pdf de OPPLUS
# Importe de la deuda (entre 50€ y 15.000€)
importe_deuda = np.random.uniform(50, 15000, n_expedientes)

# Días de impago (entre 1 y 89 días, recuerda que a los 90 explota)
dias_impago = np.random.randint(1, 90, n_expedientes)

# Prioridad inicial del banco (Baja=1, Media=2, Alta=3)
# le indico que el 60% de los casos sean prioridad 1, el 30% prioridad 2,
# y solo un 10% prioridad 3. Así es más realista, ¡no todo puede ser súper urgente!
prioridad = np.random.choice([1, 2, 3], n_expedientes, p=[0.6, 0.3, 0.1])

# Historial: Número de veces que ya hemos llamado a este cliente (entre 0 y 5 veces)
llamadas_previas = np.random.randint(0, 6, n_expedientes)

# 3. CREAMOS LA VARIABLE OBJETIVO (Lo que el Machine Learning va a predecir)
# Vamos a simular quién terminó en "Mora" (1) y quién se salvó (0).
# Calcula un "riesgo" del 0 al 1. Le doy mucho peso (60%) a estar cerca del día 90.
# Le doy un 20% de peso a tener una deuda muy grande, y otro 20% a tener prioridad alta.
# Lógicamente, a más días de impago y más deuda, más probabilidad de acabar en mora.
probabilidad_mora = (dias_impago / 90) * 0.6 + (importe_deuda / 15000) * 0.2 + (prioridad / 3) * 0.2
# SIMULACIÓN DE INCERTIDUMBRE (El factor "suerte" del mundo real)
# En lugar de usar un límite fijo (ej: si riesgo > 0.5 = mora), generamos un "umbral de suerte"
# aleatorio para cada cliente entre 0.30 y 0.90.
# Si el riesgo calculado del cliente supera su umbral aleatorio, entra en mora (1).
# Si no lo supera, se salva (0).
# Esto introduce un ruido realista en los datos para obligar al algoritmo a aprender
# patrones complejos en lugar de simples reglas matemáticas obvias.
llego_a_mora = (probabilidad_mora > np.random.uniform(0.3, 0.9, n_expedientes)).astype(int)

# 4. Juntamos todo en un DataFrame de Pandas (Tema 2)
df_opplus = pd.DataFrame({
    'ID_Cliente': range(1, n_expedientes + 1),
    'Importe_Deuda': np.round(importe_deuda, 2),
    'Dias_Impago': dias_impago,
    'Prioridad_Banco': prioridad,
    'Llamadas_Previas': llamadas_previas,
    'Llego_a_Mora': llego_a_mora # Esta es nuestra columna a predecir (Y)
})

# Mostramos los primeros 5 expedientes para ver cómo ha quedado
print("Nuestros primeros expedientes de prueba:")
display(df_opplus.head(10))

# Importamos las herramientas de Machine Learning (Scikit-Learn, del Tema 4 y 6)
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 1. SEPARAMOS LOS DATOS: Ingredientes (X) vs. Resultado esperado (Y)
# X: Las variables que usamos para decidir (quitamos el ID porque no aporta nada lógico y la columna objetivo)
X = df_opplus[['Importe_Deuda', 'Dias_Impago', 'Prioridad_Banco', 'Llamadas_Previas']]

# Y: Lo que queremos predecir (¿Llega a mora sí o no?)
Y = df_opplus['Llego_a_Mora']

# 2. ENTRENAMIENTO VS EXAMEN (Tema 4)
# Dividimos los 12.000 datos: 80% para que el modelo estudie (entrene) y 20% para hacerle un examen (test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

# 3. CREAMOS EL CEREBRO: El Árbol de Decisión (Tema 6)
# max_depth=4: Solo puede hacer 4 preguntas seguidas. Si no ponemos esto, se aprende los datos de memoria (hace trampa).
# El modelo hace 4 preguntas clave: "¿Debe mucho dinero? ¿Lleva más de 80 días? ¿Es prioridad alta? ¿Le hemos llamado poco?".
modelo_arbol = DecisionTreeClassifier(max_depth=4, random_state=0)

# 4. ENTRENAMOS AL MODELO (¡Aquí ocurre la magia!)
# .fit() procesa los datos. Aquí la máquina cruza las 4 variables y aprende sola las reglas del banco.
modelo_arbol.fit(X_train, Y_train)

# 5. HACEMOS EL EXAMEN
# Le pedimos al modelo que prediga el futuro de los clientes del 20% que no había visto
predicciones = modelo_arbol.predict(X_test)

# Comprobamos cuántas veces ha acertado
precision = accuracy_score(Y_test, predicciones)

print(f"¡Modelo entrenado! Precisión del Árbol de Decisión: {precision * 100:.2f}%")

import matplotlib.pyplot as plt
import seaborn as sns

# Le preguntamos al modelo: "¿Qué columnas han sido más importantes para tomar tus decisiones?"
importancias = modelo_arbol.feature_importances_

# Creamos un gráfico de barras bonito
plt.figure(figsize=(10, 6))
sns.barplot(x=importancias, y=X.columns, palette="viridis")
plt.title('Importancia de cada Variable en la Decisión Final', fontsize=14)
plt.xlabel('Peso en la decisión (%)')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Le recordamos a Colab cómo calcular el Score de Urgencia por si se le ha borrado
X = df_opplus[['Importe_Deuda', 'Dias_Impago', 'Prioridad_Banco', 'Llamadas_Previas']]
probabilidades = modelo_arbol.predict_proba(X)[:, 1]
df_opplus['Score_Urgencia'] = np.round(probabilidades * 100, 2)
# ----------------------------

# SIMULACIÓN DE IMPACTO ECONÓMICO
# Supongamos que hoy solo tenemos capacidad para llamar a 10,000 de los 12,000 clientes.
capacidad = 10000

# 1. Sin tu sistema (Llamadas al azar):
# Le ponemos random_state=42 para que la aleatoriedad sea siempre igual y no baile el gráfico
df_azar = df_opplus.sample(n=capacidad, random_state=42)
dinero_recuperado_azar = df_azar['Importe_Deuda'].sum()

# 2. Con tu sistema (Llamadas por Score de Urgencia):
df_sistema = df_opplus.sort_values(by='Score_Urgencia', ascending=False).head(capacidad)
dinero_recuperado_sistema = df_sistema['Importe_Deuda'].sum()

# 3. Gráfico de comparación
plt.figure(figsize=(8, 5))
labels = ['Reparto Tradicional', 'Sistema Houston (Tu App)']
valores = [dinero_recuperado_azar, dinero_recuperado_sistema]
plt.bar(labels, valores, color=['gray', '#1E88E5'])
plt.title('Dinero en Riesgo Gestionado en un solo día (€)')
plt.ylabel('Euros (€)')

ahorro = dinero_recuperado_sistema - dinero_recuperado_azar
print(f"💰 ¡BRUTAL! Solo hoy, tu sistema ha priorizado {ahorro:,.2f}€ más que el método antiguo.")
plt.show()

!pip install -q streamlit
!npm install localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.tree import DecisionTreeClassifier
# 
# st.set_page_config(page_title="OPPLUS - Triaje Inteligente", layout="wide")
# st.title("Sistema de Triaje GYAR - Equipo Houston")
# 
# # --- SECCIÓN DE SUBIDA DE DATOS ---
# st.markdown("### 1. Carga de Expedientes")
# archivo_subido = st.file_uploader("Seleccione el archivo CSV con los expedientes diarios", type=["csv"])
# 
# # --- MOTOR DE INTELIGENCIA (Se activa si hay datos) ---
# if archivo_subido is not None:
#     # Si el banco sube su archivo real, lo leemos
#     df = pd.read_csv(archivo_subido)
#     st.success("Datos operativos cargados correctamente en el sistema.")
# else:
#     # MODO DEMO
#     st.info("Modo de simulación activado: Generando 12.000 expedientes para demostración del modelo...")
#     np.random.seed(0)
#     df = pd.DataFrame({
#         'ID_Cliente': range(1, 12001),
#         'Importe_Deuda': np.round(np.random.uniform(50, 15000, 12000), 2),
#         'Dias_Impago': np.random.randint(1, 90, 12000),
#         'Prioridad_Banco': np.random.choice([1, 2, 3], 12000, p=[0.6, 0.3, 0.1]),
#         'Llamadas_Previas': np.random.randint(0, 6, 12000)
#     })
#     # Lógica de mora para entrenar en modo demo
#     prob_mora = (df['Dias_Impago'] / 90) * 0.6 + (df['Importe_Deuda'] / 15000) * 0.2 + (df['Prioridad_Banco'] / 3) * 0.2
#     df['Llego_a_Mora'] = (prob_mora > np.random.uniform(0.3, 0.9, 12000)).astype(int)
# 
# # --- ENTRENAMIENTO Y PREDICCIÓN ---
# X = df[['Importe_Deuda', 'Dias_Impago', 'Prioridad_Banco', 'Llamadas_Previas']]
# if 'Llego_a_Mora' in df.columns:
#     Y = df['Llego_a_Mora']
#     modelo = DecisionTreeClassifier(max_depth=4, random_state=0)
#     modelo.fit(X, Y)
# 
#     # Predecir riesgo
#     df['Score_Urgencia'] = np.round(modelo.predict_proba(X)[:, 1] * 100, 2)
#     df_final = df.sort_values(by='Score_Urgencia', ascending=False)
# 
#     # --- DASHBOARD VISUAL ---
#     st.divider()
#     col1, col2, col3 = st.columns(3)
#     col1.metric("Expedientes a Gestionar", f"{len(df):,}", "Volumen diario")
#     casos_criticos = len(df_final[df_final['Score_Urgencia'] > 80])
#     col2.metric("Casos Nivel Crítico (>80% Riesgo)", f"{casos_criticos}", "Prioridad Operativa", delta_color="inverse")
#     dinero_riesgo = df_final.head(casos_criticos)['Importe_Deuda'].sum()
#     col3.metric("Capital en Máximo Riesgo", f"{dinero_riesgo:,.0f} €", "Asegurado por el sistema")
# 
#     st.subheader("Bandeja de Trabajo Priorizada")
#     if st.button("Asignar casos urgentes a centralita"):
#         st.success("Casos derivados a los gestores exitosamente.")
# 
#     st.dataframe(df_final[['ID_Cliente', 'Score_Urgencia', 'Dias_Impago', 'Importe_Deuda', 'Prioridad_Banco']], use_container_width=True)